language: ruby
rvm:
- 2.4.5
sudo: false
cache: bundler
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/785e30b29dba900ebfe7
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '9.5'
install: bin/setup
after_script: bundle exec codeclimate-test-reporter
