= ManageIQ provider for KubeVirt

// Settings:
ifdef::env-github[]
:status:
endif::[]
// URIs:
:uri-gem:            http://badge.fury.io/rb/manageiq-providers-kubevirt
:badge-gem:          https://badge.fury.io/rb/manageiq-providers-kubevirt.svg
:uri-build:          https://travis-ci.org/ManageIQ/manageiq-providers-kubevirt
:badge-build:        https://travis-ci.org/ManageIQ/manageiq-providers-kubevirt.svg
:uri-codequality:    https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt
:badge-codequality:  https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt.svg
:uri-testcoverage:   https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt/badges/coverage
:badge-testcoverage: https://codeclimate.com/github/ManageIQ/manageiq-providers-kubevirt/badges/coverage.svg
:uri-dependencies:   https://gemnasium.com/ManageIQ/manageiq-providers-kubevirt
:badge-dependencies: https://gemnasium.com/ManageIQ/manageiq-providers-kubevirt.svg
:uri-security:       https://hakiri.io/github/ManageIQ/manageiq-providers-kubevirt/master
:badge-security:     https://hakiri.io/github/ManageIQ/manageiq-providers-kubevirt/master.svg
:uri-chat:           https://gitter.im/ManageIQ/manageiq-providers-kubevirt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
:badge-chat:         https://badges.gitter.im/Join%20Chat.svg
:uri-translate:      https://translate.zanata.org/zanata/project/view/manageiq-providers-kubevirt
:badge-translate:    https://img.shields.io/badge/translate-zanata-blue.svg

ifdef::status[]
image:{badge-gem}[Gem Version Badge,link={uri-gem}]
image:{badge-build}[Build Status Badge,link={uri-build}]
image:{badge-codequality}[Code Quality Badge,link={uri-codequality}]
image:{badge-testcoverage}[Test Coverage Badge,link={uri-testcoverage}]
image:{badge-dependencies}[Dependencies Badge,link={uri-dependencies}]
image:{badge-security}[Security Badge,link={uri-security}]

image:{badge-chat}[Chat Badge,link={uri-chat}]
image:{badge-translate}[Translate Badge,link={uri-translate}]
endif::[]

This repository contains an experimental provider that integrates the
http://manageiq.org[ManageIQ] and https://github.com/kubevirt[KubeVirt]
projects.

In order to make this work the `manageiq` and `manageiq-ui-classic`
projects also need to be changed, merging the commits in the
following branches:

* For the `manageiq` project:
+
https://github.com/jhernand/manageiq/tree/kubevirt_provider

* For the `manageiq-ui-classic` project:
+
https://github.com/jhernand/manageiq-ui-classic/tree/kubevirt_provider

== Things that work

Currently the provider supports the following simple use cases:

1. Add the provider using token athentication.

2. Provision virtual machines from templates.

3. Connect to the SPICE console of the virtual machines.

== Things that don't work

* The Kubernetes API suports authentication using client side digital
certificates, tokens and user name and passwords. The KubeVirt provider only
supports tokens. The UI already has the posibility to specify other
authentication mechanisms, but they don't work in the provider side yet.

* The use of client certificates should probably be part of the ManageIQ
core, as many other providers may want to support them. For example,
oVirt could use them in combination with an authentication configuration
that uses the client certificate subject as the user name.

* The UI works for initial validation and credentials, and for adding the
provider, but it doesn't work for editing the provider: it doesn't show the
selected authentication method, and it doesn't show the token.

== Things that should be changed

* Kubernetes has a `namespace` concept that is currently ignored by the
provider, it only uses the `default` namespace, and that is hard-coded.
We should consider making the namespace part of the initial dialog to
add the provider, like the authentication details or the IP address.

* In KubeVirt virtual machines are started when they are created. There is no
such thing like a virtual machine that has been created but not started. When
the provider refreshes the inventory it _archives_ all the virtual machines
that aren't running. This should be changed, so the provider should check what
virtual machines already exist in the ManageIQ database, and should avoid
removing them. In more general terms, the provider considers the KubeVirt
configuration the source of truth. That should be changed, the source of truth
should be the ManageIQ database.

* The provider doesn't have a mechanism to start/stop virtual machines, because
stopping a means removing it from KubeVirt, and that would currently remove
(actuall archive) it permanently during the next refresh. This is closely
related to the previous item. If that is addressed, then the provider will be
able to start/stop a virtual machine by creating/deleting it in KubeVirt.

* There is no event tracker. The refresh of the inventory is only performed
manually, or when a new virtual machine is added.

* The inventory refresh uses the _graph refresh_ mechanism, but it
always performs a full refresh, there are no specific targers (like
virtual machines, or hosts) implemented yet.

* The `kubeclient` gem that the provider uses to talk to the Kubernetes API
doesn't support the sub-resource mechanism used by the KubeVirt API for SPICE
details. In addition Kubernetes itself doesn't yet support sub-resources
for custom resource definitions. As a result the provider has to extract
the SPICE proxy URL from the configuration of the `spice-proxy` service.

== Notes

=== How to get the default token from Kubernetes

List the set of secrets:

  $ kubectl get secrets
  NAME                  TYPE                                  DATA      AGE
  default-token-7psxt   kubernetes.io/service-account-token   3         20d

Get the details of the `default` token:

  # kubectl get secret default-token-7psxt -o yaml
  apiVersion: v1
  data:
    ca.crt: LS0...
  namespace: ZGV...
  token: ZXl...
  ...

The token is the value of the `token` attribute, but it is encoded using
base64, so it needs to be decoded:

  $ echo ZXl... | base64 -d
  eyJ...

The extracted value can now be used to authenticate with the Kubernetes
API, setting the `Authorization` header:

  Authorization: Bearer eyJ...
