---
:ems:
  :ems_kubevirt:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :addition:
          :critical:
            - VIRTUALMACHINE_CREATED
            - VIRTUALMACHINEINSTANCE_CREATED
            - VIRTUALMACHINE_SUCCESSFULCREATE
            - VIRTUALMACHINEINSTANCE_SUCCESSFULCREATE
        :status:
          :critical:
            - VIRTUALMACHINE_MIGRATED
            - VIRTUALMACHINEINSTANCE_MIGRATED
        :power:
          :critical:
            - VIRTUALMACHINE_STARTED
            - VIRTUALMACHINEINSTANCE_STARTED
            - VIRTUALMACHINE_SHUTTINGDOWN
            - VIRTUALMACHINEINSTANCE_SHUTTINGDOWN
        :deletion:
          :critical:
            - VIRTUALMACHINE_SUCCESSFULDELETE
            - VIRTUALMACHINEINSTANCE_SUCCESSFULDELETE
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_kubevirt:
        :poll: 1.seconds
      :event_catcher_prometheus:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_kubevirt: {}
      :ems_refresh_worker:
        :ems_refresh_worker_kubevirt: {}
